### PR TITLE
generate markdown card with loop

### PR DESCRIPTION
**Pull request by mdecourcy**

### CODE REVIEW

**Comment by bdacus01** [comment]
Thanks for this.  However the base card you are using is not a "native card to HA".   Since the use of your code would seem require a HACS card called Stack In Card by RomRider.  It might be best for the mass user base for you to created the card or another example card using only native cards.  Just a suggestion.

**Comment by finity69x2** [comment]
It looks interesting.

I'll test it out when I get a chance and if it looks OK then I'll merge it in.

Thanks for the input! :)

**Comment by finity69x2** [comment]
> Thanks for this. However the base card you are using is not a "native card to HA". Since the use of your code would seem require a HACS card called Stack In Card by RomRider. It might be best for the mass user base for you to created the card or another example card using only native cards. Just a suggestion.

the original card in the package used the same card as the PR does so that's not an issue.

unless I'm missing something...

**Comment by regularguy01** [comment]
> unless I'm missing something...

I guess my point is a generalization then.   I would recommend if you want a more widely adopted plugin you need to try to code it on "native" functionality as much as possible.  Using custom functions or cards can cause people who dont have that "custom item" installed to not use the plugin.  As they perceive it doesn't work.

**Comment by mdecourcy** [comment]
> > unless I'm missing something...
> 
> I guess my point is a generalization then. I would recommend if you want a more widely adopted plugin you need to try to code it on "native" functionality as much as possible. Using custom functions or cards can cause people who dont have that "custom item" installed to not use the plugin. As they perceive it doesn't work.

Apologies for the late reply, I was on vacation in Mexico. I can amend the PR to your spec if you'd like a non-custom card, or maybe add a section to the README with card install instructions. 

Also, I just checked the difference and I noticed I dropped the first conditional on the NWS alert count, which should probably be readded. 

Let me know your thoughts.

**Comment by mdecourcy** [comment]
Writing README now, quick question: should I write it as a NWS Alerts tab, or as a "manual" card? A card install might feel more familiar than editing a tabs YAML to a majority of end users. Let me know your thoughts!

**Comment by regularguy01** [comment]
Yes I would just make it a card.

**Comment by finity69x2** [comment]
I'm going to go ahead and merge this now.

we can have a conversation about how it should be used at a later time if you want.

also remember, the integration is the main focus of this repo.

the usage is up to the end user and everything else besides the integration are just usage examples.

But I also just realized the readme never got updated to point to the new package folder location. I'll fix that.

**Comment by regularguy01** [comment]
> also remember, the integration is the main focus of this repo.

I would submit to you if you put in user examples that work fully and natively. Regular users will use the integration and find it all "works" out of the box.  Making adoption higher. 

> the usage is up to the end user and everything else besides the integration are just usage examples.

Yes you can look at it that way.  However if you look at it in a more "holistic" manor and provide an out of the box working solution it would be adopted better.

**Pull request merged**
