### PR TITLE
fix: read yaml config properly

### PR DESCRIPTION
**Pull request by firstof9**
I believe this should read the yaml config properly now.

### CODE REVIEW

**Comment by finity69x2** [comment]
I'm not sure if you meant it or not but this change is still labelled as "draft" so I can't merge it.

**Comment by firstof9** [comment]
Ya I'm still working on it, rather than have you merge a bunch of junk I'll just work on it in this draft and mark it ready once I got it going. 👍

**Comment by finity69x2** [comment]
I merged this to dev and so far it's seems to be working OK.

Are the only extra options the "timeout" & "interval"?

So there is no confusion could you clarify for me what the extra config options mean so I can properly update the install/usage instructions?

EDIT:

It seems I spoke too soon.

it works fine in the UI (even configuring multiple integrations) but it only works in YAML if I configure only one sensor.

In yaml if I configure more than one sensor using the following code:

```
sensor:
  - platform: nws_alerts
    zone_id: 'INZ009,INC033'
    name: NWS Alerts yaml
    timeout: 120
    interval: 5
  - platform: nws_alerts
    zone_id: 'ARC023'
    name: NWS Alerts yaml ark
    timeout: 120
    interval: 5
```

...I get the following error:

```
2021-07-26 16:58:00 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nws_alerts platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nws_alerts/sensor.py", line 67, in async_setup_platform
    async_add_entities([NWSAlertSensor(hass, config)], True)
  File "/config/custom_components/nws_alerts/sensor.py", line 80, in __init__
    super().__init__(hass.data[DOMAIN][entry.entry_id][COORDINATOR])
AttributeError: 'collections.OrderedDict' object has no attribute 'entry_id'
```

and only one of the sensors show up and it's always the first one configured.

If I switch the order in yaml then the "ark" sensor shows up but the plain (non-ark) "yaml" sensor doesn't and I get the above error.

```
sensor:
  - platform: nws_alerts
    zone_id: 'ARC023'
    name: NWS Alerts yaml ark
    timeout: 120
    interval: 5
  - platform: nws_alerts
    zone_id: 'INZ009,INC033'
    name: NWS Alerts yaml
    timeout: 120
    interval: 5
```

**Comment by firstof9** [comment]
Ah shoot, let me double check.

**Pull request merged**
